# Generated by Django 4.2.1 on 2023-05-12 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='citys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contectNumber', models.CharField(max_length=15)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rooms.citys')),
            ],
            options={
                'verbose_name': 'hotel',
                'verbose_name_plural': 'hotels',
            },
        ),
        migrations.CreateModel(
            name='roomCategorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='states',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNumber', models.IntegerField()),
                ('description', models.TextField()),
                ('pricePerDay', models.IntegerField()),
                ('hotelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rooms.hotels')),
                ('roomCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rooms.roomcategorys')),
            ],
        ),
        migrations.CreateModel(
            name='roomImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomImages', models.ImageField(upload_to='Rooms')),
                ('roomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rooms.rooms', verbose_name='hotel room')),
            ],
        ),
        migrations.AddField(
            model_name='hotels',
            name='roomCategory',
            field=models.ManyToManyField(to='Rooms.roomcategorys'),
        ),
        migrations.AddField(
            model_name='hotels',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rooms.states'),
        ),
        migrations.AddField(
            model_name='citys',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rooms.states'),
        ),
    ]
