# Generated by Django 4.2.1 on 2023-05-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='hotelImage',
            field=models.ImageField(default='', upload_to='Hotel_pic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomcategorys',
            name='imagepic',
            field=models.ImageField(default='', upload_to='category_images'),
            preserve_default=False,
        ),
    ]
