# Generated by Django 4.2.1 on 2023-05-15 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
        ('Rooms', '0002_hotels_hotelimage_roomcategorys_imagepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkInTime', models.DateTimeField()),
                ('checkOutTime', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rooms.rooms')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.clientuser', verbose_name='user Booked')),
            ],
        ),
    ]
