# Generated by Django 4.2.1 on 2023-05-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0003_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='roomImage',
            field=models.ImageField(default='', upload_to='roomImage'),
            preserve_default=False,
        ),
    ]
