# Generated by Django 4.2.1 on 2023-05-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0004_rooms_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='reating',
            field=models.IntegerField(default=1),
        ),
    ]
