# Generated by Django 4.2.1 on 2023-05-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0005_hotels_reating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='checkOutStatus',
            field=models.BooleanField(default=False),
        ),
    ]
