# Generated by Django 4.2.1 on 2023-05-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0006_bookings_checkoutstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='bookingStatus',
            field=models.CharField(choices=[('Running', 'Running'), ('Pending', 'pending'), ('cancelled', 'cancelled'), ('expired', 'expired')], default=2, max_length=100),
        ),
    ]
