# Generated by Django 4.2.1 on 2023-05-23 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
        ('Rooms', '0007_bookings_bookingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='bookingStatus',
            field=models.CharField(choices=[('Running', 'Running'), ('Pending', 'pending'), ('cancelled', 'cancelled'), ('expired', 'expired')], default='Pending', max_length=100),
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('msg', models.TextField(blank=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rooms.hotels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.clientuser')),
            ],
        ),
    ]
