# Generated by Django 4.2.1 on 2023-05-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('emailId', models.EmailField(max_length=254)),
                ('mobileNumber', models.CharField(max_length=13)),
                ('creatinDate', models.DateField(auto_now_add=True)),
                ('password', models.TextField()),
            ],
        ),
    ]
